feat: added new plugin method to work with html a tags
SPANDigital/presidium-html-to-markdown pull request #6
Opened 2024-08-21 19:55 UTC by noe-span

PRSDM-6086-externla-links-https-protocol

### Description

There is an issue with links that do not have the https protocol, for example
mailto, radar, etc. It may also include http

An example of a mailto link after conversion:

`http://files/mailto:aci-queue-onboarding%40group.apple.com`
Also check use of baseurl

Steps to Reproduce

Site conversion to use as a test: https://docs.aci.apple.com/kafka/index.html

Command to convert site:

convert "https://docs.aci.apple.com/kafka/" "<OUTPUT_DIR>" --select=.pageContent

### Issue
https://spandigital.atlassian.net/browse/PRSDM-6086

### files:

html content (tests):

`
<!DOCTYPE html>

<html lang="en" data-content_root="./">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  </head>
  <body>

    <header>
      <div class="headerWrapper">
        <h1 class="globalTitle" data-toc-skip=""><a href="https://aci.apple.com/">Apple Cloud Infrastructure</a></h1>
        <p><a href="https://aci.apple.com/office-hours/">Office Hours</a></p>
        <p><a href="https://docs.aci.apple.com/">Documentation</a></p>
        <p><a href="https://status.aci.apple.com/">Status</a></p>
      </div>
    </header>

    <p>
        <p><a href="https://docs.aci.apple.com/kafka/contents.html">Site Map</a></p>
        <p><a href="https://docs.aci.apple.com/kafka/public_api.html">API Docs</a></p>
        <p><a href="http://docs.aci.apple.com/kafka/contents.html">Site Map</a></p>
        <p><a href="http://docs.aci.apple.com/kafka/public_api.html">API Docs</a></p>
        <p><a href="mailto:aci-queue-support@group.apple.com" alt="contact pie">Contact</a></p>
    </p>
  </body>
</html>

`

[_index.md](https://github.com/user-attachments/files/16698052/_index.md)

### Checklist before merging

* [x] Is this code covered by tests (local)?
* [ ] Is the documentation updated for this change?

2024-08-26 11:44 UTC, Zalaras commented
@noe-span does this not cause all links to be converted like this? Does it preserve internal links?

2024-08-26 14:27 UTC, noe-span commented
@Zalaras could you please share examples of those internal html links? that way I can execute tests, share the results with you and see if the process is ok

2024-08-27 22:57 UTC, noe-span commented
@Zalaras I tested this, I do not know if those links will be like this:

HTML:

`<!DOCTYPE html>
<!-- saved from url=(0043)https://docs.aci.apple.com/kafka/index.html -->
<html lang="en" data-content_root="./">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  </head>
  <body>

    <header>
      <div class="headerWrapper">
        <h1 class="globalTitle" data-toc-skip=""><a href="https://aci.apple.com/">Apple Cloud Infrastructure</a></h1>
        <p><a href="https://aci.apple.com/office-hours/">Office Hours</a></p>
        <p><a href="https://docs.aci.apple.com/">Documentation</a></p>
        <p><a href="https://status.aci.apple.com/">Status</a></p>
      </div>
    </header>

    <p>
        <p><a href="https://docs.aci.apple.com/kafka/contents.html">Site Map</a></p>
        <p><a href="https://docs.aci.apple.com/kafka/public_api.html">API Docs</a></p>
        <p><a href="http://docs.aci.apple.com/kafka/contents.html">Site Map</a></p>
        <p><a href="http://docs.aci.apple.com/kafka/public_api.html">API Docs</a></p>
        <p><a href="mailto:aci-queue-support@group.apple.com" alt="contact pie">Contact</a></p>
        <p></p><a href="#lesson1">Lesson.1</a></p>
        <p></p><a id="lesson1">Introduction of Lesson.1</a></p>
    </p>
  </body>
</html>
`
MD:

`---
title: "Apple Cloud Infrastructure"
weight: 1
---

[Office Hours](https://aci.apple.com/office-hours/)

[Documentation](https://docs.aci.apple.com/)

[Status](https://status.aci.apple.com/)

[Site Map](https://docs.aci.apple.com/kafka/contents.html)

[API Docs](https://docs.aci.apple.com/kafka/public_api.html)

[Site Map](http://docs.aci.apple.com/kafka/contents.html)

[API Docs](http://docs.aci.apple.com/kafka/public_api.html)

[Contact](mailto:aci-queue-support@group.apple.com)

[Lesson.1](#lesson1)

[Introduction of Lesson.1](lesson1)
`
Is that ok?

2024-09-04 14:25 UTC, Zalaras requested changes
Tested locally and we are losing internal refs (links between content in the site)

Using this command:
```
go run main.go convert "https://docs.aci.apple.com/kafka/" ./output --select=.pageContent
```

output/introduction.md has 4 links:
Main branch:
```
[Apache Kafka](https://kafka.apache.org/)
[Overview]({{< ref "overview" >}})
[On-boarding & Expansion]({{< ref "onboarding" >}})
[contact us]({{< ref "contact" >}})
```
This PR:
```
[Apache Kafka](reference external)
[Overview](reference internal)
[On-boarding & Expansion](reference internal)
[contact us](reference internal)
```

In the above example we are also losing the external link

2024-09-04 20:12 UTC, noe-span commented
Hi @Zalaras I found my error, I needed to iterate in the html nodes and attributes to find the href, when we have mo complex structures in those tags mi initial code only took the class reference, since my example where simple I always got the values I needed but for your example we have style classes and more components, with the new logic now we have this:

![image](https://github.com/user-attachments/assets/51b11f44-8502-413f-b683-d060bc589841)

![image](https://github.com/user-attachments/assets/49ca27eb-a227-46a0-9bfd-75804fd5e808)

And Even with that modification my simpler example is working as in the beginning:

![image](https://github.com/user-attachments/assets/930d6ad3-b29d-4183-8574-7d417a9b7346)

Is that ok or do you think I should do more investigation an modifications?

2024-09-09 12:03 UTC, Zalaras commented
@noe-span do those links work though?

Also we need them to be in the ref shortcode format for internal links: `{{< ref "" >}}`

2024-09-10 22:45 UTC, noe-span commented
Hi @Zalaras I added changes, created more functions to split functionality and have a clearer code, now the result of the process with the same examples (mine and the one with the kafka info) are the next:

![image](https://github.com/user-attachments/assets/17904078-25fb-4f9b-b0d7-3837d5c6da1f)
![image](https://github.com/user-attachments/assets/77aaf6c4-04c9-4245-8e49-ff4262857967)


te external links are working fine the internal appear just as we see them in the apple projects for KMDS

![image](https://github.com/user-attachments/assets/4ad75b68-2b0c-4de4-a892-51f25a934ab9)


do you think that is OK or should I do more investigation/modifications?

2024-09-11 19:38 UTC, Zalaras commented
@noe-span  I see there is a `mailto:` link in your screenshots that is in a `ref` shortcode

2024-09-11 20:54 UTC, noe-span commented
@Zalaras for the mailto, it should work like an external link? only [label](link)? also that applies for rdar?, if we have a list on how it should be processed each one it would be useful, that way I can create the proper logic (In KMDS I have only worked with external and internal md articles)

2024-09-11 20:56 UTC, noe-span commented
@Zalaras the method that I need to modify would be only this:

```
func processPrefix(content string, link string) string {

	if strings.HasPrefix(link, http) || strings.HasPrefix(link, https) {
		content = "[" + content + "](" + link + ")"
	} else {
		content = "[" + content + "](" + processInternalRef(link) + ")"
	}

	return content

}
```

2024-09-11 21:07 UTC, Zalaras commented
@noe-span

Any link that goes to a page/section within the documentation would be an internal link and should use the `ref` shortcode.

Any link that goes to an external site or is a not a http/https link e.g. `mailto:` is an external link and should be left as is.

It might be easier to find the internal links by looking for the same baseurl rather than having an exception for each external link. We also don't have a list and things like rdar is custom to Apple so we can never be sure we would have a full list.

2024-09-11 22:48 UTC, noe-span commented
@Zalaras I added the next:
```

func processPrefix(content string, link string) string {

	if strings.HasPrefix(link, http) || strings.HasPrefix(link, https) || linkContainsReservedString(link) {
		content = "[" + content + "](" + link + ")"
	} else {
		content = "[" + content + "](" + processInternalRef(link) + ")"
	}

	return content

}

func linkContainsReservedString(link string) bool {

	contains := false

	for key := range getReservedStringsMap() {

		if strings.Contains(link, key) {
			contains = true
		}

	}

	return contains

}

func getReservedStringsMap() map[string]bool {

	reservedStr := map[string]bool{
		mailto: true,
		rdar:   true,
	}

	return reservedStr

}
```

but maybe a regex that describes an internal link could solve it easier as you said, but not sure how to build it 

![image](https://github.com/user-attachments/assets/68cce6a3-a494-4d9b-ac45-f52619ce4b42)


it could contain just a string + .hmtl or string + .html + # + another string, but not sure if that would cover everything speaking of html internal links

with my actual code I got:

![image](https://github.com/user-attachments/assets/ee489e9f-0564-4e68-960b-f214d835b080)


the kafka example is still working as expected

2024-09-17 20:20 UTC, noe-span commented
Hi @Zalaras, @mpilo-khathwane I thought that using a regex would be better than using the code that I push the last time, that code is working as you can see in the las comment, I been trying to work with the regex, but since GO has the prefer in the regex it is not working for all the examples making it more difficult to process:

![image](https://github.com/user-attachments/assets/30cbb2ed-791d-4228-a9c2-4b4f2d7f3c0a)

 it says that it prefers but in all my examples it always takes the left side of the expression (the x in the example image), so it will need split the string for the links

![image](https://github.com/user-attachments/assets/e53e893c-c049-4e8a-815b-0bdc38d09849)


Also we will ned to take care of the name (any possible name) in that process, so now thinking about my code it is faster, it works with a map, that map is working with the key value just to see if we have certain content to process the link, we can put that content in a config file so if we find something new that we need to have a  that behaviour  

this is from my actual code that is working
 
![image](https://github.com/user-attachments/assets/0efc49cb-7e5c-4d55-8f8a-b35f6c53430f)

we can read that from the config file 

![image](https://github.com/user-attachments/assets/b5892b3b-cbdb-41de-b85d-bfef59c4a164)

in this case the process for the external links is the one with "more logic" and calls that map method, and for the inner links is easier (instead of using the regex that needs more process)

2024-10-28 13:40 UTC, Zalaras requested changes
Still having issues, pulled the PR and all the refs have a `\` before the first `{`. While Hugo will build the site without issues the link is broken and leads to a page not found

![Screenshot 2024-10-28 at 15 39 33](https://github.com/user-attachments/assets/e8d1f873-940c-42ec-a6a0-445f6f35b9ac)

2024-10-28 22:58 UTC, noe-span commented
@Zalaras I added the changes that I used in the old commits I did, now the ref style section has that old code (prevents to use the scape character)

2024-10-29 07:07 UTC, Zalaras commented
@noe-span
- Please make sure that links are showing as expected in the site linked in the ticket.

`mailto:` are still broken:
<img width="286" alt="Screenshot 2024-10-29 at 09 00 59" src="https://github.com/user-attachments/assets/11a6e023-2c58-4b02-bea6-9bc9ff0285ce">

If the tests work then we need to look at those too and see why there is a difference between converting the site and the tests

2024-10-29 15:34 UTC, noe-span commented
@Zalaras I added the logic to process the mailto with the new logic (the rdar is working as expected
I thought I could have the same problem) the tests is with the apple-kafka url

![image](https://github.com/user-attachments/assets/af3cec30-7dbb-4b7f-9d3c-0327821d20f0)

2024-11-20 07:56 UTC, Zalaras requested changes
Additional notes:
I noticed some changes to variable names, unless they are unclear I would personally leave them, it just adds to the number of changes in the PR and can cause uncertainty about the change.
In one case I saw a one-liner moved to a one-liner function that isn't used anywhere else. If it was used somewhere else I would understand but otherwise its similar to variable names it's just extra changes that have no impact.

2024-11-20 07:56 UTC, Zalaras commented on converter/plugins.go
> +					// content = strings.Replace(content, `#`, `\#`, -1)
commented out code?

2024-11-20 07:56 UTC, Zalaras commented on converter/plugins.go
> -					return &result
You were working on links is there a reason this was removed?

2024-11-20 07:56 UTC, Zalaras commented on converter/plugins.go
> +						content = fmt.Sprintf("[%s](%s)", content, strings.Replace(href, "%40", "@", 1))
This `@` replace is for fixing the `mailto:` links? While it's unlikely for there to be a link with an `@` is there a chance this may break those types of links?

2024-11-20 07:56 UTC, Zalaras commented on converter/plugins.go
> -}
Again reason for the removal?

2024-11-20 07:56 UTC, Zalaras commented on converter/plugins.go
> +	return iniStr + cleanLink + endStr
Would `fmt.Sprintf("{{< ref \"%s\" >}}", cleanLink)` not be cleaner to read?

2024-11-20 07:56 UTC, Zalaras commented on converter/plugins.go
> +const ref = "ref"
colon is `:`, this is technically escaped quotation marks. See the other comment though I think this should just be simplified into `fmt.Sprintf("")` in the code at the end of the file

2024-11-20 07:56 UTC, Zalaras commented on converter/html_to_md.go
> +}}
Interesting formatter should have put the `}` on the newline

2024-11-20 07:56 UTC, Zalaras commented on converter/html_to_md.go
It doesn't look like all the changes in this file is related to links. Are we sure we've maintained the functionality?

2024-11-20 14:13 UTC, noe-span commented on converter/plugins.go
> -					return &result
Hi @mpilo-khathwane correct me if I'm wrong, this one with our new code (cleaner) will be processed

2024-11-20 14:13 UTC, noe-span commented on converter/plugins.go
> -}
Hi @mpilo-khathwane correct me if I'm wrong, this one with our new code (cleaner) will be processed

2024-11-20 20:34 UTC, noe-span commented on converter/html_to_md.go
> +}}
If I do that I got an error:

![image](https://github.com/user-attachments/assets/5ae7a407-e951-4f34-8514-c12865fcaf7d)

2024-11-20 20:43 UTC, noe-span commented
Hi @Zalaras @mpilo-khathwane I did some modifications (commented lines and formatted string) for the functionality deleted, the code was cleared and we just added the methods we need to process the remaining issues (External and internal links)

2024-11-27 13:16 UTC, Zalaras approved these changes
Cool, nice work. I'm approving but just get @mpilo-khathwane  to double check or maybe do a rebase to cleanup. Once he's approved I'm happy for you to merge

2024-12-10 15:39 UTC, merged